import bcrypt from 'bcryptjs';
import {
  UserRole,
  PaymentStatus,
  PaymentMethod,
  LatePaymentChargeMode,
  LatePaymentChargeStatus,
  TicketStatus,
  TicketPriority,
  QueueStatus,
  AppointmentStatus,
  AppointmentType,
  NotificationType,
} from '../types/index.js';

export function getInitialSeedData() {
  const defaultPasswordHash = bcrypt.hashSync('Password123!', 10);

  // 1. Users
  const users = [
    // Students
    {
      id: 'USR_STU_1',
      email: 'student1@ucu.ac.ug',
      password_hash: defaultPasswordHash,
      full_name: 'Jane Namukasa',
      phone: '+256 772 123 456',
      role: UserRole.STUDENT,
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      created_at: '2026-01-10T08:00:00Z',
      updated_at: '2026-01-10T08:00:00Z',
    },
    {
      id: 'USR_STU_2',
      email: 'student2@ucu.ac.ug',
      password_hash: defaultPasswordHash,
      full_name: 'Brian Okello',
      phone: '+256 701 987 654',
      role: UserRole.STUDENT,
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      created_at: '2026-01-11T09:00:00Z',
      updated_at: '2026-01-11T09:00:00Z',
    },
    {
      id: 'USR_STU_3',
      email: 'student3@ucu.ac.ug',
      password_hash: defaultPasswordHash,
      full_name: 'Joshua Kigozi',
      phone: '+256 782 345 678',
      role: UserRole.STUDENT,
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      created_at: '2026-01-12T10:00:00Z',
      updated_at: '2026-01-12T10:00:00Z',
    },
    {
      id: 'USR_STU_4',
      email: 'student4@ucu.ac.ug',
      password_hash: defaultPasswordHash,
      full_name: 'Grace Akello',
      phone: '+256 752 876 543',
      role: UserRole.STUDENT,
      avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      created_at: '2026-01-12T11:00:00Z',
      updated_at: '2026-01-12T11:00:00Z',
    },
    {
      id: 'USR_STU_5',
      email: 'student5@ucu.ac.ug',
      password_hash: defaultPasswordHash,
      full_name: 'Daniel Mukisa',
      phone: '+256 703 112 233',
      role: UserRole.STUDENT,
      avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      created_at: '2026-01-13T12:00:00Z',
      updated_at: '2026-01-13T12:00:00Z',
    },
    // Staff
    {
      id: 'USR_STAFF_1',
      email: 'officer@ucu.ac.ug',
      password_hash: defaultPasswordHash,
      full_name: 'Sarah Tumusiime',
      phone: '+256 772 445 566',
      role: UserRole.ACCOUNTS_OFFICER,
      avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      created_at: '2025-08-01T08:00:00Z',
      updated_at: '2025-08-01T08:00:00Z',
    },
    {
      id: 'USR_STAFF_2',
      email: 'senior@ucu.ac.ug',
      password_hash: defaultPasswordHash,
      full_name: 'Patrick Mukasa',
      phone: '+256 701 556 677',
      role: UserRole.SENIOR_ACCOUNTS_OFFICER,
      avatar_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
      created_at: '2025-07-01T08:00:00Z',
      updated_at: '2025-07-01T08:00:00Z',
    },
    {
      id: 'USR_STAFF_3',
      email: 'supervisor@ucu.ac.ug',
      password_hash: defaultPasswordHash,
      full_name: 'Dr. Florence Kembabazi',
      phone: '+256 782 667 788',
      role: UserRole.ACCOUNTS_SUPERVISOR,
      avatar_url: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80',
      created_at: '2025-06-01T08:00:00Z',
      updated_at: '2025-06-01T08:00:00Z',
    },
  ];

  // 2. Students
  const students = [
    {
      id: 'STU_1',
      user_id: 'USR_STU_1',
      student_number: 'S22B14/001',
      registration_number: 'A92831',
      programme: 'Bachelor of Science in Information Technology (BSIT)',
      faculty: 'Faculty of Science & Technology',
      campus: 'Main Campus - Mukono',
      has_financial_hold: false,
      financial_hold_reason: null,
      created_at: '2026-01-10T08:00:00Z',
    },
    {
      id: 'STU_2',
      user_id: 'USR_STU_2',
      student_number: 'S23B23/045',
      registration_number: 'B81729',
      programme: 'Bachelor of Business Administration (BBA)',
      faculty: 'School of Business',
      campus: 'Main Campus - Mukono',
      has_financial_hold: false,
      financial_hold_reason: null,
      created_at: '2026-01-11T09:00:00Z',
    },
    {
      id: 'STU_3',
      user_id: 'USR_STU_3',
      student_number: 'S21B11/089',
      registration_number: 'L73921',
      programme: 'Bachelor of Laws (LLB)',
      faculty: 'Faculty of Law',
      campus: 'Main Campus - Mukono',
      has_financial_hold: false,
      financial_hold_reason: null,
      created_at: '2026-01-12T10:00:00Z',
    },
    {
      id: 'STU_4',
      user_id: 'USR_STU_4',
      student_number: 'S22B15/012',
      registration_number: 'N62819',
      programme: 'Bachelor of Nursing Science (BNS)',
      faculty: 'School of Medicine & Dentistry',
      campus: 'Mengo Campus',
      has_financial_hold: false,
      financial_hold_reason: null,
      created_at: '2026-01-12T11:00:00Z',
    },
    {
      id: 'STU_5',
      user_id: 'USR_STU_5',
      student_number: 'S20B11/003',
      registration_number: 'T51920',
      programme: 'Bachelor of Divinity (Theology)',
      faculty: 'Bishop Tucker School of Divinity',
      campus: 'Main Campus - Mukono',
      has_financial_hold: false,
      financial_hold_reason: null,
      created_at: '2026-01-13T12:00:00Z',
    },
  ];

  // 3. Accounts Staff
  const accountsStaff = [
    {
      id: 'STF_1',
      user_id: 'USR_STAFF_1',
      staff_number: 'ACC/2022/014',
      title: 'Accounts Officer — Front Desk & Verifications',
      assigned_counter: 'Counter 1 — General Financial Enquiries',
      is_available_for_queue: true,
      max_active_tickets: 15,
      created_at: '2025-08-01T08:00:00Z',
    },
    {
      id: 'STF_2',
      user_id: 'USR_STAFF_2',
      staff_number: 'ACC/2019/007',
      title: 'Senior Accounts Officer — Escalations & Disputes',
      assigned_counter: 'Counter 2 — Senior Officer & Disputes',
      is_available_for_queue: true,
      max_active_tickets: 10,
      created_at: '2025-07-01T08:00:00Z',
    },
    {
      id: 'STF_3',
      user_id: 'USR_STAFF_3',
      staff_number: 'ACC/2015/002',
      title: 'Accounts Supervisor / Financial Systems Manager',
      assigned_counter: 'Office Suite A3 — Accounts Directorate',
      is_available_for_queue: false,
      max_active_tickets: 5,
      created_at: '2025-06-01T08:00:00Z',
    },
  ];

  // 4. Financial Accounts
  // Jane Namukasa: Assessed 2,400,000 | Verified 1,440,000 (60%) | Balance 960,000 | 45% Achieved
  // Brian Okello: Assessed 2,000,000 | Verified 600,000 (30%) | Balance 1,400,000 | 45% Pending (Needs 300,000)
  // Joshua Kigozi: Assessed 3,000,000 | Verified 1,350,000 (45%) | Balance 1,650,000 | 45% Exactly Achieved
  // Grace Akello: Assessed 2,800,000 | Verified 2,100,000 (75%) | Balance 700,000 | 75% Mid-sem Achieved
  // Daniel Mukisa: Assessed 1,800,000 | Verified 1,800,000 (100%) | Balance 0 | 100% Final Clearance
  const financialAccounts = [
    {
      id: 'FIN_ACC_1',
      student_id: 'STU_1',
      semester_id: 'SEM_EASTER_2026',
      assessed_tuition: 2200000,
      other_assessed_fees: 200000,
      total_assessed: 2400000,
      verified_amount_paid: 1440000,
      pending_amount_paid: 0,
      outstanding_balance: 960000,
      payment_percentage: 60.0,
      has_late_charges_assessed: false,
      total_late_charges: 0,
      updated_at: '2026-02-10T14:30:00Z',
    },
    {
      id: 'FIN_ACC_2',
      student_id: 'STU_2',
      semester_id: 'SEM_EASTER_2026',
      assessed_tuition: 1800000,
      other_assessed_fees: 200000,
      total_assessed: 2000000,
      verified_amount_paid: 600000,
      pending_amount_paid: 200000, // Has a 200,000 pending verification!
      outstanding_balance: 1400000,
      payment_percentage: 30.0,
      has_late_charges_assessed: true,
      total_late_charges: 50000,
      updated_at: '2026-02-14T09:15:00Z',
    },
    {
      id: 'FIN_ACC_3',
      student_id: 'STU_3',
      semester_id: 'SEM_EASTER_2026',
      assessed_tuition: 2700000,
      other_assessed_fees: 300000,
      total_assessed: 3000000,
      verified_amount_paid: 1350000,
      pending_amount_paid: 0,
      outstanding_balance: 1650000,
      payment_percentage: 45.0,
      has_late_charges_assessed: false,
      total_late_charges: 0,
      updated_at: '2026-02-12T11:00:00Z',
    },
    {
      id: 'FIN_ACC_4',
      student_id: 'STU_4',
      semester_id: 'SEM_EASTER_2026',
      assessed_tuition: 2500000,
      other_assessed_fees: 300000,
      total_assessed: 2800000,
      verified_amount_paid: 2100000,
      pending_amount_paid: 0,
      outstanding_balance: 700000,
      payment_percentage: 75.0,
      has_late_charges_assessed: false,
      total_late_charges: 0,
      updated_at: '2026-02-18T16:00:00Z',
    },
    {
      id: 'FIN_ACC_5',
      student_id: 'STU_5',
      semester_id: 'SEM_EASTER_2026',
      assessed_tuition: 1600000,
      other_assessed_fees: 200000,
      total_assessed: 1800000,
      verified_amount_paid: 1800000,
      pending_amount_paid: 0,
      outstanding_balance: 0,
      payment_percentage: 100.0,
      has_late_charges_assessed: false,
      total_late_charges: 0,
      updated_at: '2026-02-20T10:00:00Z',
    },
  ];

  // 5. Payments
  const payments = [
    {
      id: 'PAY_1',
      student_id: 'STU_1',
      semester_id: 'SEM_EASTER_2026',
      transaction_reference: 'STAN-2026-009182',
      amount: 1440000,
      payment_date: '2026-01-20',
      payment_method: PaymentMethod.STANBIC_BANK,
      status: PaymentStatus.VERIFIED,
      notes: 'Initial tuition deposit for Easter Semester 2026',
      proof_document_url: '/uploads/stanbic_slip_009182.pdf',
      submitted_at: '2026-01-20T11:20:00Z',
      verified_by: 'STF_1',
      verified_at: '2026-01-20T14:30:00Z',
      rejection_reason: null,
    },
    {
      id: 'PAY_2',
      student_id: 'STU_2',
      semester_id: 'SEM_EASTER_2026',
      transaction_reference: 'CENT-2026-118273',
      amount: 600000,
      payment_date: '2026-01-25',
      payment_method: PaymentMethod.CENTENARY_BANK,
      status: PaymentStatus.VERIFIED,
      notes: 'Partial deposit via Centenary Bank Mukono Branch',
      proof_document_url: '/uploads/cent_slip_118273.pdf',
      submitted_at: '2026-01-25T10:15:00Z',
      verified_by: 'STF_1',
      verified_at: '2026-01-25T11:45:00Z',
      rejection_reason: null,
    },
    {
      id: 'PAY_3',
      student_id: 'STU_2',
      semester_id: 'SEM_EASTER_2026',
      transaction_reference: 'MTN-MM-2026-992182',
      amount: 200000,
      payment_date: '2026-02-14',
      payment_method: PaymentMethod.MTN_MOBILE_MONEY,
      status: PaymentStatus.PENDING_VERIFICATION, // Awaiting verification!
      notes: 'Submitted via MTN Mobile Money merchant code 182731',
      proof_document_url: '/uploads/mtn_sms_992182.jpg',
      submitted_at: '2026-02-14T09:10:00Z',
      verified_by: null,
      verified_at: null,
      rejection_reason: null,
    },
    {
      id: 'PAY_4',
      student_id: 'STU_3',
      semester_id: 'SEM_EASTER_2026',
      transaction_reference: 'ABSA-2026-448192',
      amount: 1350000,
      payment_date: '2026-02-02',
      payment_method: PaymentMethod.ABSA_BANK,
      status: PaymentStatus.VERIFIED,
      notes: 'Direct wire deposit to UCU Law Faculty fees account',
      proof_document_url: '/uploads/absa_receipt_448192.pdf',
      submitted_at: '2026-02-02T13:00:00Z',
      verified_by: 'STF_1',
      verified_at: '2026-02-02T15:20:00Z',
      rejection_reason: null,
    },
    {
      id: 'PAY_5',
      student_id: 'STU_4',
      semester_id: 'SEM_EASTER_2026',
      transaction_reference: 'EQUITY-2026-339102',
      amount: 2100000,
      payment_date: '2026-02-05',
      payment_method: PaymentMethod.EQUITY_BANK,
      status: PaymentStatus.VERIFIED,
      notes: 'Nursing clinical and semester tuition full 75% tranche',
      proof_document_url: '/uploads/equity_slip_339102.pdf',
      submitted_at: '2026-02-05T09:30:00Z',
      verified_by: 'STF_2',
      verified_at: '2026-02-05T10:45:00Z',
      rejection_reason: null,
    },
    {
      id: 'PAY_6',
      student_id: 'STU_5',
      semester_id: 'SEM_EASTER_2026',
      transaction_reference: 'STAN-2026-882910',
      amount: 1800000,
      payment_date: '2026-01-18',
      payment_method: PaymentMethod.STANBIC_BANK,
      status: PaymentStatus.VERIFIED,
      notes: 'Full 100% semester tuition payment',
      proof_document_url: '/uploads/stanbic_slip_882910.pdf',
      submitted_at: '2026-01-18T10:00:00Z',
      verified_by: 'STF_1',
      verified_at: '2026-01-18T11:15:00Z',
      rejection_reason: null,
    },
    {
      id: 'PAY_7_REJECTED',
      student_id: 'STU_1',
      semester_id: 'SEM_EASTER_2026',
      transaction_reference: 'AIRTEL-MM-2026-004128',
      amount: 100000,
      payment_date: '2026-02-08',
      payment_method: PaymentMethod.AIRTEL_MONEY,
      status: PaymentStatus.REJECTED,
      notes: 'Invalid bank statement - transaction reversed by telecom provider',
      proof_document_url: null,
      submitted_at: '2026-02-08T14:00:00Z',
      verified_by: 'STF_1',
      verified_at: '2026-02-09T09:00:00Z',
      rejection_reason: 'Transaction ID failed telecom reconciliation check. Amount was reversed to sender.',
    },
  ];

  // 6. Receipts
  const receipts = [
    {
      id: 'REC_1',
      receipt_number: 'UCU-REC-2026-0001',
      payment_id: 'PAY_1',
      student_id: 'STU_1',
      semester_id: 'SEM_EASTER_2026',
      amount: 1440000,
      currency: 'UGX',
      transaction_reference: 'STAN-2026-009182',
      payment_date: '2026-01-20',
      verification_date: '2026-01-20T14:30:00Z',
      verified_by_staff_name: 'Sarah Tumusiime (Accounts Officer)',
      download_count: 2,
      created_at: '2026-01-20T14:30:05Z',
    },
    {
      id: 'REC_2',
      receipt_number: 'UCU-REC-2026-0002',
      payment_id: 'PAY_2',
      student_id: 'STU_2',
      semester_id: 'SEM_EASTER_2026',
      amount: 600000,
      currency: 'UGX',
      transaction_reference: 'CENT-2026-118273',
      payment_date: '2026-01-25',
      verification_date: '2026-01-25T11:45:00Z',
      verified_by_staff_name: 'Sarah Tumusiime (Accounts Officer)',
      download_count: 1,
      created_at: '2026-01-25T11:45:10Z',
    },
    {
      id: 'REC_4',
      receipt_number: 'UCU-REC-2026-0003',
      payment_id: 'PAY_4',
      student_id: 'STU_3',
      semester_id: 'SEM_EASTER_2026',
      amount: 1350000,
      currency: 'UGX',
      transaction_reference: 'ABSA-2026-448192',
      payment_date: '2026-02-02',
      verification_date: '2026-02-02T15:20:00Z',
      verified_by_staff_name: 'Sarah Tumusiime (Accounts Officer)',
      download_count: 1,
      created_at: '2026-02-02T15:20:15Z',
    },
    {
      id: 'REC_5',
      receipt_number: 'UCU-REC-2026-0004',
      payment_id: 'PAY_5',
      student_id: 'STU_4',
      semester_id: 'SEM_EASTER_2026',
      amount: 2100000,
      currency: 'UGX',
      transaction_reference: 'EQUITY-2026-339102',
      payment_date: '2026-02-05',
      verification_date: '2026-02-05T10:45:00Z',
      verified_by_staff_name: 'Patrick Mukasa (Senior Accounts Officer)',
      download_count: 3,
      created_at: '2026-02-05T10:45:20Z',
    },
    {
      id: 'REC_6',
      receipt_number: 'UCU-REC-2026-0005',
      payment_id: 'PAY_6',
      student_id: 'STU_5',
      semester_id: 'SEM_EASTER_2026',
      amount: 1800000,
      currency: 'UGX',
      transaction_reference: 'STAN-2026-882910',
      payment_date: '2026-01-18',
      verification_date: '2026-01-18T11:15:00Z',
      verified_by_staff_name: 'Sarah Tumusiime (Accounts Officer)',
      download_count: 5,
      created_at: '2026-01-18T11:15:25Z',
    },
  ];

  // 7. Late-Payment Charges
  const latePaymentCharges = [
    {
      id: 'LATE_CHG_1',
      student_id: 'STU_2',
      semester_id: 'SEM_EASTER_2026',
      milestone_id: 'MS_REG_2026',
      amount: 50000,
      reason: 'Failed to attain the mandatory 45% registration payment milestone prior to the February 15 statutory deadline.',
      charge_mode: LatePaymentChargeMode.ONCE_PER_MILESTONE,
      assessment_date: '2026-02-16',
      status: LatePaymentChargeStatus.ASSESSED,
      waived_by: null,
      waived_at: null,
      waiver_reason: null,
      created_at: '2026-02-16T00:01:00Z',
    },
  ];

  // 8. Tickets
  const tickets = [
    {
      id: 'TCK_1',
      ticket_number: 'ACC-2026-0001',
      student_id: 'STU_1',
      student_number: 'S22B14/001',
      student_name: 'Jane Namukasa',
      service_id: 'SRV_CLEARANCE',
      service_name: 'Semester Financial Clearance',
      category: 'Financial Clearance & Eligibility',
      description: 'Requesting confirmation of 45% clearance to proceed with module selection on Alpha MIS.',
      priority: TicketPriority.NORMAL,
      status: TicketStatus.RESOLVED,
      assigned_staff_id: 'STF_1',
      assigned_staff_name: 'Sarah Tumusiime',
      queue_id: null,
      expected_resolution_time: '2026-01-21T17:00:00Z',
      actual_resolution_time: '2026-01-21T14:10:00Z',
      resolution_summary: 'Verified 60% cumulative payment. Clearance token cleared to University Academic Portal.',
      is_escalated: false,
      escalation_reason: null,
      student_feedback_rating: 5,
      student_feedback_comments: 'Prompt response and accurate guidance. Thank you!',
      created_at: '2026-01-21T10:00:00Z',
      updated_at: '2026-01-21T14:10:00Z',
    },
    {
      id: 'TCK_2',
      ticket_number: 'ACC-2026-0002',
      student_id: 'STU_2',
      student_number: 'S23B23/045',
      student_name: 'Brian Okello',
      service_id: 'SRV_PAY_NOT_REFLECTED',
      service_name: 'Payment Not Reflected',
      category: 'Inquiries & Disputes',
      description: 'Paid UGX 200,000 via MTN Mobile Money on Feb 14 morning. Requesting urgent verification to lift registration block.',
      priority: TicketPriority.HIGH,
      status: TicketStatus.IN_PROGRESS,
      assigned_staff_id: 'STF_1',
      assigned_staff_name: 'Sarah Tumusiime',
      queue_id: null,
      expected_resolution_time: '2026-02-15T12:00:00Z',
      actual_resolution_time: null,
      resolution_summary: null,
      is_escalated: false,
      escalation_reason: null,
      student_feedback_rating: null,
      student_feedback_comments: null,
      created_at: '2026-02-14T09:30:00Z',
      updated_at: '2026-02-14T11:00:00Z',
    },
    {
      id: 'TCK_3',
      ticket_number: 'ACC-2026-0003',
      student_id: 'STU_2',
      student_number: 'S23B23/045',
      student_name: 'Brian Okello',
      service_id: 'SRV_LATE_CHARGE_REV',
      service_name: 'Late-Payment Charge Review',
      category: 'Inquiries & Disputes',
      description: 'Appeal for waiver of UGX 50,000 late payment charge. Payment was submitted on Feb 14 prior to deadline.',
      priority: TicketPriority.HIGH,
      status: TicketStatus.ESCALATED,
      assigned_staff_id: 'STF_2',
      assigned_staff_name: 'Patrick Mukasa',
      queue_id: null,
      expected_resolution_time: '2026-02-17T17:00:00Z',
      actual_resolution_time: null,
      resolution_summary: null,
      is_escalated: true,
      escalation_reason: 'Student claims bank delay occurred during statutory weekend window. Escalated to Senior Officer for waiver appraisal.',
      student_feedback_rating: null,
      student_feedback_comments: null,
      created_at: '2026-02-16T10:00:00Z',
      updated_at: '2026-02-16T11:30:00Z',
    },
  ];

  // 9. Ticket Messages
  const ticketMessages = [
    {
      id: 'MSG_1',
      ticket_id: 'TCK_2',
      sender_user_id: 'USR_STU_2',
      sender_name: 'Brian Okello',
      sender_role: UserRole.STUDENT,
      message: 'Hello Accounts Office, I have uploaded the MTN confirmation SMS screenshot for UGX 200,000. Please verify so my registration status updates.',
      is_internal_only: false,
      attachment_url: '/uploads/mtn_sms_992182.jpg',
      created_at: '2026-02-14T09:30:00Z',
    },
    {
      id: 'MSG_2',
      ticket_id: 'TCK_2',
      sender_user_id: 'USR_STAFF_1',
      sender_name: 'Sarah Tumusiime (Accounts Officer)',
      sender_role: UserRole.ACCOUNTS_OFFICER,
      message: 'Good morning Brian. We have logged your transaction reference MTN-MM-2026-992182 and sent it to the telecom reconciliation desk. Please allow 1-2 hours.',
      is_internal_only: false,
      attachment_url: null,
      created_at: '2026-02-14T11:00:00Z',
    },
    {
      id: 'MSG_3',
      ticket_id: 'TCK_3',
      sender_user_id: 'USR_STAFF_1',
      sender_name: 'Sarah Tumusiime',
      sender_role: UserRole.ACCOUNTS_OFFICER,
      message: 'INTERNAL NOTE: Brian has a pending mobile money transaction from Feb 14. If verified, his payment reaches 40% (still under 45%). Escalating to Senior Officer for waiver policy review.',
      is_internal_only: true,
      attachment_url: null,
      created_at: '2026-02-16T11:15:00Z',
    },
  ];

  // 10. Virtual Queue Entries
  const queueEntries = [
    {
      id: 'Q_ENT_1',
      queue_number: 'ACC-Q-2026-0001',
      student_id: 'STU_3',
      student_number: 'S21B11/089',
      student_name: 'Joshua Kigozi',
      service_id: 'SRV_VIRTUAL_QUEUE',
      service_name: 'Accounts Virtual Queue',
      ticket_id: null,
      priority: TicketPriority.NORMAL,
      status: QueueStatus.COMPLETED,
      position: 0,
      assigned_counter: 'Counter 1 — General Financial Enquiries',
      assigned_staff_id: 'STF_1',
      assigned_staff_name: 'Sarah Tumusiime',
      estimated_wait_minutes: 0,
      called_at: '2026-02-17T09:15:00Z',
      served_at: '2026-02-17T09:20:00Z',
      completed_at: '2026-02-17T09:35:00Z',
      created_at: '2026-02-17T09:00:00Z',
    },
    {
      id: 'Q_ENT_2',
      queue_number: 'ACC-Q-2026-0004',
      student_id: 'STU_1',
      student_number: 'S22B14/001',
      student_name: 'Jane Namukasa',
      service_id: 'SRV_VIRTUAL_QUEUE',
      service_name: 'Accounts Virtual Queue',
      ticket_id: null,
      priority: TicketPriority.NORMAL,
      status: QueueStatus.SERVING,
      position: 1,
      assigned_counter: 'Counter 1 — General Financial Enquiries',
      assigned_staff_id: 'STF_1',
      assigned_staff_name: 'Sarah Tumusiime',
      estimated_wait_minutes: 0,
      called_at: '2026-02-17T10:00:00Z',
      served_at: '2026-02-17T10:05:00Z',
      completed_at: null,
      created_at: '2026-02-17T09:40:00Z',
    },
    {
      id: 'Q_ENT_3',
      queue_number: 'ACC-Q-2026-0005',
      student_id: 'STU_2',
      student_number: 'S23B23/045',
      student_name: 'Brian Okello',
      service_id: 'SRV_BAL_DISPUTE',
      service_name: 'Balance Dispute',
      ticket_id: 'TCK_3',
      priority: TicketPriority.HIGH,
      status: QueueStatus.WAITING,
      position: 2,
      assigned_counter: 'Counter 2 — Senior Officer & Disputes',
      assigned_staff_id: 'STF_2',
      assigned_staff_name: 'Patrick Mukasa',
      estimated_wait_minutes: 10,
      called_at: null,
      served_at: null,
      completed_at: null,
      created_at: '2026-02-17T09:55:00Z',
    },
  ];

  // 11. Appointments
  const appointments = [
    {
      id: 'APT_1',
      appointment_number: 'ACC-APT-2026-0001',
      student_id: 'STU_1',
      student_number: 'S22B14/001',
      student_name: 'Jane Namukasa',
      service_id: 'SRV_APPOINTMENT_BOOK',
      service_name: 'Accounts Appointment Booking',
      staff_id: 'STF_1',
      staff_name: 'Sarah Tumusiime',
      appointment_type: AppointmentType.REMOTE,
      scheduled_date: '2026-02-22',
      time_slot: '10:00 - 10:30',
      status: AppointmentStatus.SCHEDULED,
      meeting_link_or_counter: 'https://meet.google.com/ucu-acc-tumu',
      reason: 'Consultation on 75% installment plan before mid-semester examination lock.',
      staff_notes: 'Bring proof of banking direct debit mandate if applicable.',
      created_at: '2026-02-15T14:00:00Z',
    },
    {
      id: 'APT_2',
      appointment_number: 'ACC-APT-2026-0002',
      student_id: 'STU_4',
      student_number: 'S22B15/012',
      student_name: 'Grace Akello',
      service_id: 'SRV_FIN_CONSULT',
      service_name: 'Financial Consultation',
      staff_id: 'STF_2',
      staff_name: 'Patrick Mukasa',
      appointment_type: AppointmentType.PHYSICAL,
      scheduled_date: '2026-02-23',
      time_slot: '14:00 - 14:30',
      status: AppointmentStatus.CONFIRMED,
      meeting_link_or_counter: 'Counter 2 — Senior Officer & Disputes',
      reason: 'Nursing clinical training sponsorship disbursement paperwork audit.',
      staff_notes: 'Confirmed by Senior Officer.',
      created_at: '2026-02-16T09:30:00Z',
    },
  ];

  // 12. Notifications
  const notifications = [
    {
      id: 'NOTIF_1',
      recipient_user_id: 'USR_STU_1',
      type: NotificationType.REGISTRATION_ELIGIBILITY_ACHIEVED,
      title: 'Registration Eligibility Achieved (60%)',
      message: 'Congratulations Jane! Your verified cumulative payment has reached 60%, exceeding the 45% minimum financial registration threshold.',
      is_read: false,
      entity_id: 'SEM_EASTER_2026',
      created_at: '2026-01-20T14:31:00Z',
    },
    {
      id: 'NOTIF_2',
      recipient_user_id: 'USR_STU_1',
      type: NotificationType.RECEIPT_GENERATED,
      title: 'Official Receipt Generated: UCU-REC-2026-0001',
      message: 'Your payment of UGX 1,440,000 (STAN-2026-009182) has been verified. Download your authentic UCU Accounts Office PDF receipt.',
      is_read: true,
      entity_id: 'REC_1',
      created_at: '2026-01-20T14:30:10Z',
    },
    {
      id: 'NOTIF_3',
      recipient_user_id: 'USR_STU_2',
      type: NotificationType.REGISTRATION_ELIGIBILITY_BLOCKED,
      title: 'Financial Registration Warning (30%)',
      message: 'Your current verified payment percentage is 30%. You require an additional UGX 300,000 verified payment to attain the 45% registration milestone.',
      is_read: false,
      entity_id: 'SEM_EASTER_2026',
      created_at: '2026-02-14T08:00:00Z',
    },
    {
      id: 'NOTIF_4',
      recipient_user_id: 'USR_STU_2',
      type: NotificationType.LATE_PAYMENT_CHARGE_ASSESSED,
      title: 'Late Payment Charge Assessed: UGX 50,000',
      message: 'A statutory late payment charge of UGX 50,000 has been assessed for missing the Registration milestone deadline.',
      is_read: false,
      entity_id: 'LATE_CHG_1',
      created_at: '2026-02-16T00:05:00Z',
    },
  ];

  // 13. Audit Logs
  const auditLogs = [
    {
      id: 'AUD_1',
      user_id: 'USR_STAFF_1',
      user_role: UserRole.ACCOUNTS_OFFICER,
      user_name: 'Sarah Tumusiime',
      action: 'PAYMENT_VERIFIED',
      entity_type: 'PAYMENT',
      entity_id: 'PAY_1',
      old_value: 'PENDING_VERIFICATION',
      new_value: 'VERIFIED',
      details: 'Verified Stanbic Bank transaction STAN-2026-009182 for UGX 1,440,000 against bank clearing file.',
      timestamp: '2026-01-20T14:30:00Z',
    },
    {
      id: 'AUD_2',
      user_id: 'USR_STAFF_1',
      user_role: UserRole.ACCOUNTS_OFFICER,
      user_name: 'Sarah Tumusiime',
      action: 'RECEIPT_ISSUED',
      entity_type: 'RECEIPT',
      entity_id: 'REC_1',
      old_value: null,
      new_value: 'UCU-REC-2026-0001',
      details: 'Generated official electronic receipt for Jane Namukasa (S22B14/001).',
      timestamp: '2026-01-20T14:30:05Z',
    },
    {
      id: 'AUD_3',
      user_id: 'USR_STAFF_3',
      user_role: UserRole.ACCOUNTS_SUPERVISOR,
      user_name: 'Dr. Florence Kembabazi',
      action: 'FINANCIAL_POLICY_UPDATE',
      entity_type: 'SEMESTER_PAYMENT_POLICY',
      entity_id: 'POL_EASTER_2026',
      old_value: 'Late Fee: 50,000 UGX, Reg: 45%',
      new_value: 'Late Fee: 50,000 UGX, Reg: 45%, Mid: 75%',
      details: 'Confirmed statutory payment milestone thresholds for Easter Semester 2026.',
      timestamp: '2026-01-15T09:00:00Z',
    },
  ];

  return {
    users,
    students,
    accountsStaff,
    financialAccounts,
    payments,
    receipts,
    latePaymentCharges,
    tickets,
    ticketMessages,
    queueEntries,
    appointments,
    notifications,
    auditLogs,
  };
}
